version: '3.8'

services:
  {{ values.containerName }}:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    container_name: {{ values.containerName }}

volumes:
  {{ values.containerName }}-data: