replicaCount: 1
image:
  repository: pavan176/final-enc-dec
  pullPolicy: IfNotPresent
  tag: final-enc-dec-dev-latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 8000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: final-enc-dec-dev.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 50M
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
